version: '3.5'

services:
  asp-app:
    build: .
    image: capstone:latest
    volumes:
      - .:/app
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - asp-app

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=capstone
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=secret
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network

